config/routes.rb
Rails.application.routes.draw do
  root 'users#upload'
  resources :users, only: [] do
    collection do
      get 'upload'
      post 'import'
    end
    get 'display_users', on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, :last_name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def self.import_from_excel(file)
    import_results = { total: 0, success: 0, failed: 0, reasons: [] }
    spreadsheet = Roo::Excelx.new(file.path)
    (2..spreadsheet.last_row).each do |i|
      row = spreadsheet.row(i)
      user_data = { first_name: row[0], last_name: row[1], email: row[2] }
      user = new(user_data)
      if user.save
        import_results[:success] += 1
      else
        import_results[:failed] += 1
        import_results[:reasons] << { row: i, errors: user.errors.full_messages }
      end

      import_results[:total] += 1
    end
    import_results
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def upload
  end
  def import
    file = params[:file]
    if file
      @import_results = User.import_from_excel(file)
      redirect_to display_users_users_path(import_results: @import_results)
    else
      flash[:error] = 'Please select a file to import.'
      redirect_to users_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExcelDataImporter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/display_users.html.erb
<h2>Import Results</h2>
<p>Total User Data Rows: <%= params["import_results"]["total"] %></p>
<p>Successful Imports: <%= params["import_results"]["success"] %></p>
<p>Failed Imports: <%= params["import_results"]["failed"] %></p>
<% if params[:import_results][:failed].to_i > 0 %>
  <h3>Failed Import Reasons:</h3>
  <ul>
    <% params[:import_results][:reasons].each do |reason| %>
      <li>Row <%= reason[:row] %>: <%= reason[:errors].join(', ') %></li>
    <% end %>
  </ul>
<% end %>
<%= link_to 'Back', root_path, class: 'btn btn-primary' %>

app/views/users/upload.html.erb
<%= form_tag import_users_path, multipart: true, class: 'upload-form' do %>
  <h2>Upload an Excel Sheet</h2>
  <%= file_field_tag :file, class: 'file-input' %>
  <%= submit_tag 'Upload Excel Sheet', class: 'btn btn-primary' %>
<% end %>